Integra.Web/Controllers/ContaController.cs
using System.Collections.Generic;
using System.Data.SqlClient;
using Integra.Dominio.Repositorios;
using Integra.Repositorio.EF.Repositorios;
using Integra.ServicosDeAplicacao;
using Integra.ServicosDeAplicacao.Mensagens.Perfil;
using Integra.ServicosDeAplicacao.Mensagens.Pessoa;
using Integra.ServicosDeAplicacao.Mensagens.Programa;
using Integra.ServicosDeAplicacao.Mensagens.Usuario;
using Integra.Web.CustomMembership;
using Integra.Web.Helpers;
using Integra.Web.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace Integra.Web.Controllers
{
    public class ContaController : BaseController
    {
        private readonly PessoaServicoDeAplicacao _pessoaServicoDeAplicacao;
        private readonly ProgramaServicoDeAplicacao _programaServicoDeAplicacao;
        private readonly PerfilServicoDeAplicacao _perfilServicoDeAplicacao;
        private readonly ITipoDeCrmRepositorio _tipoDeCrmRepositorio;
        private readonly IPerfilRepositorio _perfilRepositorio;
        private readonly IGrupoRepositorio _grupoRepositorio;
        private readonly ICargoRepositorio _cargoRepositorio;
        private readonly IDepartamentoRepositorio _departamentoRepositorio;
        private readonly IProgramaRepositorio _programaRepositorio;
        private readonly IModuloRepositorio _moduloRepositorio;
        private readonly IPessoaRepositorio _pessoaRepositorio;
        private readonly IClienteRepositorio _clienteRepositorio;
        private readonly IFuncionarioRepositorio _funcionarioRepositorio;

        public ContaController(ITipoDeCrmRepositorio tipoDeCrmRepositorio, IPerfilRepositorio perfilRepositorio,
            IGrupoRepositorio grupoRepositorio, ICargoRepositorio cargoRepositorio, IDepartamentoRepositorio departamentoRepositorio
            , IProgramaRepositorio programaRepositorio, IModuloRepositorio moduloRepositorio, IPessoaRepositorio pessoaRepositorio
            , IClienteRepositorio clienteRepositorio, IFuncionarioRepositorio funcionarioRepositorio,
            PerfilServicoDeAplicacao perfilServicoDeAplicacao, PessoaServicoDeAplicacao pessoaServicoDeAplicacao, ProgramaServicoDeAplicacao programaServicoDeAplicacao)
        {
            _tipoDeCrmRepositorio = tipoDeCrmRepositorio;
            _perfilRepositorio = perfilRepositorio;
            _grupoRepositorio = grupoRepositorio;
            _cargoRepositorio = cargoRepositorio;
            _departamentoRepositorio = departamentoRepositorio;
            _programaRepositorio = programaRepositorio;
            _moduloRepositorio = moduloRepositorio;
            _pessoaRepositorio = pessoaRepositorio;
            _clienteRepositorio = clienteRepositorio;
            _funcionarioRepositorio = funcionarioRepositorio;
            _perfilServicoDeAplicacao = perfilServicoDeAplicacao;

            _pessoaServicoDeAplicacao = pessoaServicoDeAplicacao;
            _programaServicoDeAplicacao = programaServicoDeAplicacao;
        }

        [AuthorizeCustom(Modulo = "GestaoUsuario")]
        public ActionResult Index()
        {
            return View(_pessoaRepositorio.ObterTodos().ToViewModel());
        }

        public PartialViewResult AlterarSenha()
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult AlterarSenha(AlterarSenhaViewModel viewModel)
        {
            if (SecurityHelper.Authenticate(User.ToPessoa().Usuario.NomeDeUsuario, viewModel.Senha))
            {
                var requisicao = new AlterarSenhaRequisicao
                                     {
                                         CodigoDaPessoa = User.ToPessoa().Codigo,
                                         NovaSenha = viewModel.NovaSenha
                                     };
                var resposta = _pessoaServicoDeAplicacao.AlterarSenha(requisicao);
                return Json(resposta);
            }
            return Json(new { Sucesso = false });
        }


        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            try
            {
                if (SecurityHelper.Authenticate(model.NomeDeUsuario, model.Senha))
                {
                    FormsAuthentication.SetAuthCookie(model.NomeDeUsuario, model.Relembrar);
                    var pessoa = _pessoaServicoDeAplicacao.RegistrarAcesso(model.NomeDeUsuario);
                    Session.SetProgramaAtivo(pessoa.ProgramasPermitidos[0]);
                    return Redirect(string.IsNullOrWhiteSpace(model.ReturnUrl) ? Url.Action("Index", "Relatorios") : model.ReturnUrl);
                }
            }
            catch (Exception exception)
            {
                ViewBag.HasError = true;
                Error(exception.Message);
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            SecurityHelper.Logout();
            return RedirectToAction("Login");
        }


        [AuthorizeCustom(Modulo = "GestaoUsuario")]
        public ActionResult Editar(int id)
        {
            var perfils =
                _perfilRepositorio.ObterTodos().Select(t => new { t.Codigo, t.Nome, CodigoDoGrupo = t.Grupo.Codigo });
            var grupoIntegra = _grupoRepositorio.ObterGrupoIntegra();
            var grupos = _grupoRepositorio.ObterTodos().Select(t => new { t.Codigo, t.Descricao });
            var tipos = _tipoDeCrmRepositorio.ObterTodos().ToList();
            var departamentos = _departamentoRepositorio.ObterTodos().ToList();
            var cargos = _cargoRepositorio.ObterTodos().ToList();
            var programas = _programaRepositorio.ObterTodos().ToList();
            var novoUsuario = new AdicionarUsuarioViewModel
                                  {
                                      Perfils = perfils,
                                      Grupos = grupos,
                                      TiposDeCrm = tipos,
                                      Cargos = cargos,
                                      Departamentos = departamentos,
                                      GrupoIntegra = grupoIntegra,
                                      Programas = programas
                                  };

            var cliente = _clienteRepositorio.ObterPor(id);
            if (cliente == null)
            {
                var funcionario = _funcionarioRepositorio.ObterPor(id);
                novoUsuario.Codigo = funcionario.Codigo;
                novoUsuario.PerfilSelecionado = funcionario.Usuario.Perfil.Codigo;
                novoUsuario.NomeDeUsuario = funcionario.Usuario.NomeDeUsuario;
                novoUsuario.GrupoSelecionado = funcionario.Usuario.Perfil.Grupo.Codigo;
                novoUsuario.CodigoDoCargo = funcionario.Cargo != null ? funcionario.Cargo.Codigo : 1;
                novoUsuario.CodigoDoDepartamento = funcionario.Departamento != null ? funcionario.Departamento.Codigo : 1;
                novoUsuario.Nome = funcionario.Nome;
                novoUsuario.Telefone = funcionario.Telefone;
                novoUsuario.Status = funcionario.Inativo;
                novoUsuario.CodigosDosProgramas = funcionario.ProgramasPermitidos.Select(it => it.Codigo).ToList();
                novoUsuario.DescricaoDoCargo = funcionario.Descricao;
            }
            else
            {
                novoUsuario.Codigo = cliente.Codigo;
                novoUsuario.PerfilSelecionado = cliente.Usuario.Perfil.Codigo;
                novoUsuario.NomeDeUsuario = cliente.Usuario.NomeDeUsuario;
                novoUsuario.GrupoSelecionado = cliente.Usuario.Perfil.Grupo.Codigo;
                novoUsuario.Nome = cliente.Nome;
                if (cliente.Crm != null)
                {
                    novoUsuario.NumeroDoCrm = cliente.Crm.NumeroDoCRM;
                    novoUsuario.TipoDeCrmSelecionado = cliente.Crm.Tipo.Codigo;
                    novoUsuario.NomeDoCrm = cliente.Crm.NomeDoCRM;
                }
                novoUsuario.Telefone = cliente.Telefone;
                novoUsuario.Status = cliente.Inativo;
                novoUsuario.CodigosDosProgramas = cliente.ProgramasPermitidos.Select(it => it.Codigo).ToList();

            }

            return View("NovoUsuario", novoUsuario);
        }


        [AuthorizeCustom(Modulo = "GestaoUsuario")]
        public ActionResult NovoUsuario()
        {
            var perfils = _perfilRepositorio.ObterTodos().Select(t => new { t.Codigo, t.Nome, CodigoDoGrupo = t.Grupo.Codigo });
            var grupoIntegra = _grupoRepositorio.ObterGrupoIntegra();
            var grupos = _grupoRepositorio.ObterTodos().Select(t => new { t.Codigo, t.Descricao });
            var tipos = _tipoDeCrmRepositorio.ObterTodos().ToList();
            var departamentos = _departamentoRepositorio.ObterTodos().ToList();
            var cargos = _cargoRepositorio.ObterTodos().ToList();
            var programas = _programaRepositorio.ObterTodos().ToList();
            var novoUsuario = new AdicionarUsuarioViewModel
                                  {
                                      Perfils = perfils,
                                      Grupos = grupos,
                                      TiposDeCrm = tipos,
                                      Cargos = cargos,
                                      Departamentos = departamentos,
                                      GrupoIntegra = grupoIntegra,
                                      Programas = programas
                                  };

            return View(novoUsuario);
        }

        [HttpPost]
        [AuthorizeCustom(Modulo = "GestaoUsuario")]

Integra.Web/Views/Shared/Errors.cshtml
@model HandleErrorInfo
@if (Model != null && HttpContext.Current.IsDebuggingEnabled)
{
    <div>
        <p>
            <b>Exception:</b> @Model.Exception.Message<br />
            <b>Controller:</b> @Model.ControllerName<br />
            <b>Action:</b> @Model.ActionName
        </p>
        <div style="overflow: scroll">
            <pre>
                    @Model.Exception.StackTrace
                </pre>
        </div>
    </div>
}

Integra.Web/Views/Shared/_LayoutHeader.cshtml
@using Integra.Web.CustomMembership
@using Integra.Web.Helpers
<div class="LayoutHeader">
    <div class="LayoutHeader-inner">
        <div class="container" id="HeaderPrincipal">
            <div class="LayoutHeader-logo">
                <!-- Tamanho máximo para logo: 240x60 -->
                <!-- Logo deverá mudar se caso o usuário for do Grupo Cliente e tiver o Gestor de Clínicas ativo -->
                <a href="@Url.Action("Index", "Home", new { })">
                    @if (User.ToPessoa().Usuario.PertenceAoGrupo(ViewBag.GrupoIntegra))
                    {
                        <img src='@Url.Content("~/Content/images/LogoIntegra.png")' alt="Íntegra Medical" />
                    }
                    else
                    {

                        switch (Session.ProgramaAtivo().Codigo)
                        {
                            case 1:
                        <img src='@Url.Content("~/Content/images/LogoEssencial.fw.png")' alt="Programa Essencial" />;
                                                                                                                    break;
                            case 2:
                        <img src='@Url.Content("~/Content/images/LogoJuntosElivres.png")' alt="Programa Juntos e Livres" />;
                                                                                                                           break;
                            case 3:
                        <img src='@Url.Content("~/Content/images/LogoBemEstar.png")' alt="Programa Bem Estar" />   
                                                                                                                           break;
                            case 4:
                        <img src='@Url.Content("~/Content/images/LogoProMemoria.png")' alt="Programa Pró Memória" />   
                                                                                                                           break;
                            case 5:
                        <img src='@Url.Content("~/Content/images/LogoFazBem.png")' alt="Programa Faz Bem" />   
                                                                                                                           break;
                            case 6:
                        <img src='@Url.Content("~/Content/images/LogoCoaguchek.png")' alt="Programa Coaguchek" />   
                                                                                                                           break;
                            case 7:
                        <img src='@Url.Content("~/Content/images/LogoProCaps.png")' alt="Programa ProCaps" />   
                                                                                                                           break;
                            case 8:
                        <img src='@Url.Content("~/Content/images/LogoEnzimais.png")' alt="Programa Enzimais" />   
                                                                                                                           break;
                            case 9:
                        <img src='@Url.Content("~/Content/images/LogoInclusao.png")' alt="Programa Inclusão" />   
                                                                                                                           break;
                            case 10:
                        <img src='@Url.Content("~/Content/images/LogoInspiracao.png")' alt="Programa Inspiração" />   
                                                                                                                           break;
                            case 11:
                        <img src='@Url.Content("~/Content/images/LogoOmnitrope.png")' alt="Programa Omnitrope" />   
                                                                                                                           break;
                            case 12:
                        <img src='@Url.Content("~/Content/images/LogoPorqueVerEViver.png")' alt="Programa Porque ver é viver" />   
                                                                                                                           break;
                            case 13:
                        <img src='@Url.Content("~/Content/images/LogoForever.png")' alt="Programa Porque ver é viver" />   
                                                                                                                           break;
                            default:
                        <img src='@Url.Content("~/Content/images/LogoEssencial.fw.png")' alt="Programa Essencial" />;
                                                                                                                    break;
                        }


                        //  <img src='@Url.Content("~/Content/images/LogoEssencial.fw.png")' alt="Programa Essencial" />
                    }
                </a>
            </div>

            <div id="DivFoto" class="LayoutHeader-photo" style="vertical-align: middle;">
                <!-- Tamanho máximo para foto: 100x101 -->
                <a data-bind="click: AlterarFoto" style="cursor: pointer;">
                    <img width="100" height="101" src='@Url.Action("Foto", "Home")' alt="Foto" />
                </a>
                <div style="display: none;" data-bind="dialog: { isOpen: TrocarFotoDialog, modal: true, title: '', width: '0px', height: '0px' }">
                    <div data-bind="html: TrocarFotoHtml"></div>
                </div>
            </div>

            @if (User.ToPessoa() != null)
            {
                var pessoa = User.ToPessoa(); 
                @Html.Raw("<div class='LayoutHeader-lastAccess'> Último acesso <i>")
                @pessoa.Usuario.PenultimoAcesso.ToString("dd/MM/yyyy 'as' HH:mm")
                @Html.Raw(@"</i></div><div class='LayoutHeader-information'>")
                <b>Bem vindo(a), @pessoa.Nome</b>
                <br />
                <i>@pessoa.Usuario.NomeDeUsuario   </i>

                @Html.Raw("</div>")
            }
            <div class="LayoutHeader-Logout">
                <table>
                    <tr>
                        @if (User.ToPessoa().Usuario.PertenceAoGrupo(ViewBag.GrupoIntegra))
                        {
                            <td style="display: none;">
                                <div class="LayoutHeader-Logout AlteraSenha-link">
                                    @Html.ActionLink("Central de Desenvolvimento", "Desenvolvimento", "Home", new { }, new { })
                                </div>
                            </td>
                        }
                        <td>
                            <div id="DivAlterarSenha">
                                <div class="LayoutHeader-Logout Ajuda-link">
                                    <a data-bind="click: AlterarSenha" style="cursor: pointer;">Alterar Senha
                                    </a>
                                </div>

                                <div style="display: none;" data-bind="dialog: { isOpen: AlterarSenhaDialog, modal: true, title: '', width: '0px', height: '0px' }">
                                    <div data-bind="html: AlterarSenhaHtml"></div>
                                </div>
                            </div>
                        </td>
                        @if (User.ToPessoa().Usuario.PertenceAoGrupo(ViewBag.GrupoIntegra))
                        {
                            <td>
                                <div class="LayoutHeader-Logout Ajuda-link">
                                    @Html.ActionLink("Ajuda", "Ajuda", "Home", new { }, new { })
                                </div>
                            </td>
                        }
                        <td>
                            <div class="LayoutHeader-Logout Sair-link">
                                @if (User.Identity is UsuarioIdentity)
                                {
                                    var usuarioIdentity = User.Identity as UsuarioIdentity;
                                    if (usuarioIdentity != null)
                                    {
                                    @Html.ActionLink("Sair", "Logout", "Conta")           
                                    }
                                }
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="LayoutHeader-line">
            </div>


            <div class="LayoutHeader-barra">
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <div class="LayoutHeader-barra canto">
                            </div>
                        </td>
                        <td>
                            <div class="LayoutHeader-barra barra" id="#InformacoesDoPrograma">
                                <b>Programa:</b> <i>@Session.ProgramaAtivo().Descricao</i>
                                <button class="btn-link" data-bind="click: TrocarDePrograma, visible: ProgramasPermitidos().length > 0" title="Alternar Programa"><i class="icon-refresh icon-white"></i></button>
                                <div style="display: none;" data-bind="dialog: { isOpen: AlterarProgramaDialog, modal: true, title: '', width: '0px', height: '0px' }">
                                    <div class="modal">
                                        <div class="modal-header">
                                            <h4>Alternar Programa</h4>
                                        </div>
                                        <div class="modal-body">
                                            <!-- ko foreach: ProgramasPermitidos -->
                                            <label>
                                                <input type="radio" name="programaPermitido" data-bind="value: Codigo, checked: $root.ProgramaSelecionado" /><span data-bind="    text: Nome"></span></label>
                                            <!-- /ko -->
                                        </div>
                                        <div class="modal-footer">
                                            <button data-bind="click: CancelarTrocaPrograma" class="bbtnn bbtnn-gray" value="Cancelar">Cancelar</button>
                                            <button data-bind="click: ConfirmarTrocaPrograma" class="bbtnn bbtnn-success" value="Alternar Programa">Alternar</button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="ProgramasPermitidos" value="@Json.Encode(User.ToPessoa().ProgramasPermitidos.Select(it => new { it.Codigo, it.Nome, Cheked = false }))"/>
<script>
    function AlterarFotoView() {
        var self = this;

        self.TrocarFotoDialog = ko.observable(false);
        self.TrocarFotoHtml = ko.observable();
        self.ProgramaSelecionado = ko.observable(@Session.ProgramaAtivo().Codigo);
        self.ProgramasPermitidos = ko.observableArray(jQuery.parseJSON($("#ProgramasPermitidos").val()));

        // --------------------------------------------------
        // ---- Alterar Imagem
        self.AlterarFoto = function () {
            self.TrocarFotoHtml(null);
            $.get('@Url.Action("AlterarFoto", "Home")', null, function (html) {
                self.TrocarFotoHtml(html);
                new window.AlterarFotoFactory(self);
                self.TrocarFotoDialog(true);
            });
        };

        self.CancelarNovaFoto = function () {
            self.TrocarFotoDialog(false);
            self.TrocarFotoHtml(null);
        };

        self.FecharNovaFoto = function (foto) {
            self.TrocarFotoDialog(false);
            self.TrocarFotoHtml(null);
        };

        self.AlterarSenhaDialog = ko.observable(false);
        self.AlterarSenhaHtml = ko.observable();

        // --------------------------------------------------
        // ---- Alterar Senha
        self.AlterarSenha = function () {
            self.AlterarSenhaHtml(null);
            $.get('@Url.Action("AlterarSenha", "Conta")', null, function (html) {
                self.AlterarSenhaHtml(html);
                new window.AlterarSenhaFactory(self);
                self.AlterarSenhaDialog(true);
            });
        };

        self.EfetuarAlterarSenha = function () {
            self.AlterarSenhaHtml(null);
            self.AlterarSenhaDialog(false);
        };

        self.CancelarAlterarSenha = function () {
            self.AlterarSenhaHtml(null);
            self.AlterarSenhaDialog(false);
        };

        self.AlterarProgramaDialog = ko.observable(false);
        self.TrocarDePrograma = function () {
            self.AlterarProgramaDialog(true);
        };

        self.CancelarTrocaPrograma = function () {
            self.AlterarProgramaDialog(false);
        };

        self.ConfirmarTrocaPrograma = function () {
            $.post('@Url.Action("TrocarProgramaAtivo", "Home")', { codigo: parseInt(self.ProgramaSelecionado()) }, function (retorno) {
                if (retorno)
                    document.location.reload();
            });
            self.AlterarProgramaDialog(false);
        };
    }

    $(document).ready(function () {
        var alterarFotoView = new AlterarFotoView();
        ko.applyBindings(alterarFotoView, $("#HeaderPrincipal").get(0));

        $(".ui-dialog-titlebar").hide();
        $(".ui-dialog-buttonpane").hide();
    });
</script>

Integra.Web/Views/Shared/_LayoutMaster.empty.cshtml
@using Integra.Web.CustomMembership
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>@ViewBag.Title</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	@Styles.Render("~/content/css")
	<style type="text/css">
		.form-signin {
			max-width: 300px;
			padding: 19px 29px 29px;
			margin: 0 auto 20px;
			background-color: #fff;
			border: 1px solid #e5e5e5;
			-webkit-border-radius: 5px;
			-moz-border-radius: 5px;
			border-radius: 5px;
			-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
			-moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
			box-shadow: 0 1px 2px rgba(0,0,0,.05);
		}

			.form-signin .form-signin-heading,
			.form-signin .checkbox {
				margin-bottom: 10px;
			}

			.form-signin input[type="text"],
			.form-signin input[type="password"] {
				font-size: 16px;
				height: auto;
				margin-bottom: 15px;
				padding: 7px 9px;
			}
	</style>

	<style>
		body, html {
			min-width: 1024px;
			margin: 0;
			padding: 0;
			font-family: arial, verdana, freesans, garuda, helvetica, sans-serif;
		}

		#page_overlay {
			width: 100%;
			z-index: 2;
		}

		#page_content {
			font-size: 30px;
			padding: 10px;
			background-color: #000000;
			color: #ffffff;
			margin-top: 40px;
			/* Display on top of slideshow */
			z-index: 2;
			position: relative; /* This is very important! */
		}

		img#bg {
			/* Regras de preenchimento do fundo */
			min-height: 100%;
			min-width: 1024px;
			/* Seleção de escala apropriada */
			width: 100%;
			height: auto;
			/* Posicionamento da Imagem */
			position: fixed;
			top: 0;
			left: 0;
			z-index: 0;
		}

		#bg_grid {
			position: fixed; /* This is very important! */
			top: 0;
			left: 0;
			height: 100%;
			width: 100%;
			background: url(../../Content/images/grid.png) repeat;
			/* Display on top of background */
			z-index: 1;
		}

		#bg_login {
			position: absolute;
			right: 0;
			top: 140px;
			width: 50%;
			min-width: 400px;
			height: 300px;
			background-color: #ffffff;
			z-index: 3;
		}

		#line_login {
			position: absolute;
			right: 0;
			bottom: 0;
			width: 100%;
			height: 15px;
			background-color: #62c3cf;
			z-index: 4;
		}

		#logo_login {
			position: absolute;
			z-index: 6;
			top: 40px;
			left: 90px;
		}

		#container_login {
			position: absolute;
			z-index: 7;
			top: 130px;
			left: -60px;
		}
	</style>

	@Scripts.Render("~/bundles/modernizr")
	@RenderSection("head", required: false)
	@Html.Partial("_html5shiv")
	@* favicons and touch icons go here *@
</head>
<body>
	<img id="bg" style="display: none" />

	<div id="bg_grid">
	</div>

	<div id="bg_login">
		<div id="logo_login">
			<img src='@Url.Content("~/Content/images/LogoIntegra.png")' />
		</div>
		<div id="container_login">
			<div>
				@Html.Partial("_alerts")
				@if (User.Identity is UsuarioIdentity)
				{
					var usuarioIdentity = User.Identity as UsuarioIdentity;
					if (usuarioIdentity != null)
					{
					@usuarioIdentity.Pessoa.Nome
					@Html.ActionLink("Logout", "Logout", "Conta")           
					}
				}
				@RenderBody()
			</div>
		</div>
		<div id="line_login"></div>
	</div>
	@Html.Partial("_LayoutFooter")
	<!-- container -->
	@Scripts.Render("~/js")
	@Scripts.Render("~/jsValidate")
	@RenderSection("Scripts", required: false)

	<script type="text/javascript">
		$(document).ready(function () {
			$("img#bg").load(function () {
				$("img#bg").fadeTo(1000, 1);
			}
			);
			setTimeout(LoadImage, 100);
		});

		function LoadImage() {
			$("img#bg").attr("src", '@Url.Content("~/Content/images/layout_login_background.jpg")');
		};
	</script>
</body>
</html>

Integra.Web/Views/Shared/_MenuPainelDeControle.cshtml
@using Integra.Web.Helpers
@Html.ActionLink("Projeto", "Index", "PainelDeControle", new { }, new { @class = "brand", onclick = "javascript:return false;", style = "cursor:default;" })
<div class="nav-collapse collapse">
    <ul class="nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Atendimento&nbsp;<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Abertura de Chamados", "ChamadosOnline", "PainelDeControle", new { }, new { })</li>
                <li>@Html.ActionLink("Ouvidoria", "Ouvidoria", "PainelDeControle", new { }, new { })</li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dados do Projeto&nbsp;<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Documentos do Projeto", "AprovacaoOnline", "PainelDeControle", new { }, new { })</li>
                <li>@Html.ActionLink("Equipe", "Equipe", "PainelDeControle", new { }, new { })</li>
                <li>@Html.ActionLink("Investimentos", "Faturamento", "PainelDeControle", new { }, new { })</li>
                <li>@Html.ActionLink("Serviços Contratados", "ServicosContratados", "PainelDeControle", new { }, new { })</li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Histórico do Projeto&nbsp;<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Reuniões", "Reunioes", "PainelDeControle", new { }, new { })</li>
                <li>@Html.ActionLink("Treinamentos", "Treinamentos", "PainelDeControle", new { }, new { })</li>
            </ul>
        </li>
        @*        @if (User.ToPessoa().Usuario.PertenceAoGrupo(ViewBag.GrupoIntegra))
        { 
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gerenciamento&nbsp;<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Usuários", "Index", "Conta", new { }, new { })</li>
                </ul>
            </li>
        }*@
    </ul>
    @*@if (User.ToPessoa().Usuario.PertenceAoGrupo(ViewBag.GrupoIntegra))
    {
        *@
    <ul class="nav pull-right">
        <li><a href="@Url.Action("Index", "Home", new { })" class="brand">
            <i class='icon-home'></i>Ínicio
        </a></li>
    </ul>
    @*}*@
</div>